title: Giuseppe Tinti # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Scientist with 2+ years of commercial experience in recommendation, Forecast and LLM.
  <br><br>
  <a href="https://www.linkedin.com/in/giuseppetinti/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'